export const projectData = [
  {
    title: "cli-loaders",
    imgUrl: "https://repository-images.githubusercontent.com/912560031/de9f3f22-c3a1-4a4d-92f0-4042688be63c",
    alt: "Image for christians cli loaders project",
    description: "A collection of around 100 cli loaders for the terminal and beyond",
    repo: "https://github.com/cbmongithub/cli-loaders",
    href: "https://cliloaders.com",
    date: "Jan 16 2025",
  },
  {
    title: "react-snippets",
    imgUrl: "https://repository-images.githubusercontent.com/908404327/4d4183a5-1147-49c5-bd5e-70678580c95f",
    alt: "Image for christians react snippets project",
    description: "Collection of dark mode components powered by Next 15, React 19, and Tailwind v4.",
    repo: "https://github.com/cbmongithub/react-snippets",
    href: "react-snippetss.vercel.app",
    date: "Jul 23 2024",
  },
  {
    title: "qwizr",
    imgUrl: "https://repository-images.githubusercontent.com/735717651/01270b48-523a-4787-9162-c4d4359ed17b",
    alt: "Image for christians portfolio site project",
    description: "A full stack app for quizzes on web development",
    repo: "https://github.com/cbmongithub/qwizr",
    href: "https://qwizr.netlify.app",
    date: "Jul 23 2024",
  },
  {
    title: "cbm_2022",
    imgUrl: "https://github.com/cbmongithub/cbm_2022/raw/main/public/cbm2022img.jpg",
    alt: "Image for christians portfolio site project",
    description: "My 2022 portfolio site",
    repo: "https://github.com/cbmongithub/cbm_2022",
    href: "https://cbm-2022.vercel.app/",
    date: "Mar 13 2022",
  },
  {
    title: "cbm_2023",
    imgUrl: "https://github.com/cbmongithub/cbm_2023/raw/main/public/img/md-image.jpg",
    alt: "Image for christians portfolio site project",
    description: "My 2023 portfolio site",
    repo: "https://github.com/cbmongithub/cbm_2023",
    href: "https://cbm-2023.vercel.app/",
    date: "Jul 11 2023",
  },
  // {
  //   title: "Colorfill App",
  //   imgUrl: "https://github.com/cbmongithub/colorfill/raw/main/colorfill.jpg",
  //   alt: "Image for christians colorfill app project",
  //   description: "A css tool that configures text fill animations. Also available on npm.",
  //   repo: "https://github.com/cbmongithub/colorfill",
  //   href: "https://colorfillapp.vercel.app/",
  //   date: "Jan 26 2022",
  // },
  {
    title: "Full Stack Blog",
    imgUrl:
      "https://github.com/cbmongithub/tech-blog/raw/main/public/assets/img/techblog.jpg",
    alt: "Image for christians full stack blog project",
    description: "A full stack tech blog written with MVC architecture",
    repo: "https://github.com/cbmongithub/tech-blog",
    href: "https://guarded-ocean-61686-3600ffdf6cf0.herokuapp.com/",
    date: "Feb 19 2024",
  },
  {
    title: "chattr",
    imgUrl: "https://github.com/cbmongithub/mmbc/raw/main/public/assets/mmbc.jpg",
    alt: "Image for christians mmbc website project",
    description: "A chatgpt chatbot component library for nextjs",
    repo: "https://github.com/cbmongithub/chattr",
    href: "https://www.npmjs.com/package/chattr",
    date: "Mar 22 2024",
  },
  // {
  //   title: "MMBC Consulting",
  //   imgUrl: "https://github.com/christianbmartinez/mmbc/raw/main/public/assets/mmbc.jpg",
  //   alt: "Image for christians employee tracker project",
  //   description: "React SPA for M&M Business Consulting",
  //   repo: "https://github.com/cbmongithub/mmbc",
  //   href: "https://mmbcconsulting.vercel.app/",
  //   date: "May 15 2024",
  // },
  // {
  //   title: "Mysteryboard",
  //   imgUrl: "https://github.com/cbmongithub/mysteryboard/raw/main/public/mysteryboard.jpg",
  //   alt: "Image for christians mysteryboard project",
  //   description: "A full stack application that allows users to post anonymously.",
  //   repo: "https://github.com/cbmongithub/mysteryboard",
  //   href: "https://mysteryboard.herokuapp.com/",
  //   date: "Dec 10 2024",
  // },
  {
    title: "Tic Tac Toe",
    imgUrl: "https://github.com/cbmongithub/tic-tac-toe/raw/main/md-image.jpg",
    alt: "Image for christians portfolio tic tac toe project",
    description:
      "A tic tac toe multiplayer game with chat. Built with Next, Socketio, and Express.",
    repo: "https://github.com/cbmongithub/tic-tac-toe",
    href: "https://tictactoenextjs.netlify.app/",
    date: "Jul 10 2023",
  },
  {
    title: "Create Chattr App",
    imgUrl:
      "https://github.com/cbmongithub/create-chattr-app/raw/main/public/createchattrapp.jpg",
    alt: "Image for christians portfolio create-chattr-app project",
    description: "A Nextjs chatbot boilerplate that uses the chattr library.",
    repo: "https://github.com/cbmongithub/create-chattr-app",
    href: "https://create-chattr-app.vercel.app/",
    date: "Apr 10 2024",
  },
  // {
  //   title: "Logo Generator",
  //   imgUrl:
  //     "https://github.com/cbmongithub/svg-logo-generator/raw/main/svglogogenerator.jpg",
  //   alt: "Image for christians portfolio SVG Logo generator project",
  //   description: "A node cli application for generating quality svg logos",
  //   repo: "https://github.com/cbmongithub/svg-logo-generator",
  //   href: "https://drive.google.com/file/d/1Tg1iBDdUqCIz06HrNIAeVbb3j-26K3-V/view",
  //   date: "Mar 10 2022",
  // },
];