export const portfolioData = [
  {
    title: "cbm_2022",
    imgUrl: "https://github.com/christianbmartinez/cbm_2022/raw/main/public/cbm2022img.jpg",
    alt: "Image for christians portfolio site project",
    description: "My old portfolio site built with react, bootstrap, and threejs.",
    repo: "https://github.com/christianbmartinez/cbm_2022",
    href: "https://cbm-2022.vercel.app/",
    date: "Dec 10 2024",
  },
  {
    title: "cbm_2023",
    imgUrl: "https://github.com/christianbmartinez/cbm_2023/raw/main/public/img/md-image.jpg",
    alt: "Image for christians portfolio site project",
    description: "My 2023 portfolio site built next js and tailwind.",
    repo: "https://github.com/christianbmartinez/cbm_2023",
    href: "https://cbm-2023.vercel.app/",
    date: "Dec 10 2024",
  },
  {
    title: "Colorfill App",
    imgUrl: "https://github.com/christianbmartinez/colorfill/raw/main/colorfill.jpg",
    alt: "Image for christians colorfill app project",
    description: "A css tool that configures text fill animations. Also available on npm.",
    repo: "https://github.com/christianbmartinez/colorfill",
    href: "https://colorfillapp.vercel.app/",
    date: "Dec 10 2022",
  },
  {
    title: "Full Stack Blog",
    imgUrl:
      "https://github.com/christianbmartinez/tech-blog/raw/main/public/assets/img/techblog.jpg",
    alt: "Image for christians full stack blog project",
    description: "A full stack tech blog written with MVC architecture",
    repo: "https://github.com/christianbmartinez/tech-blog",
    href: "https://guarded-ocean-61686-3600ffdf6cf0.herokuapp.com/",
    date: "Dec 10 2024",
  },
  {
    title: "Consulting Site",
    imgUrl: "https://github.com/christianbmartinez/mmbc/raw/main/public/assets/mmbc.jpg",
    alt: "Image for christians mmbc website project",
    description: "A single page application built with react and tailwind.",
    repo: "https://github.com/christianbmartinez/mmbc",
    href: "https://www.mmbc.llc/",
    date: "Dec 10 2024",
  },
  {
    title: "Employee Tracker",
    imgUrl: "https://github.com/christianbmartinez/employee-tracker/raw/main/employeetracker.jpg",
    alt: "Image for christians employee tracker project",
    description: "A node cli application that uses mysql to manage employees.",
    repo: "https://github.com/christianbmartinez/employee-tracker",
    href: "https://drive.google.com/file/d/1uLsYvFhE-2sl5wxVCUevMd-yZhQ4aVN0/view",
    date: "Dec 10 2024",
  },
  {
    title: "Mysteryboard",
    imgUrl: "https://github.com/christianbmartinez/mysteryboard/raw/main/public/mysteryboard.jpg",
    alt: "Image for christians mysteryboard project",
    description: "A full stack application that allows users to post anonymously.",
    repo: "https://github.com/christianbmartinez/mysteryboard",
    href: "https://mysteryboard.herokuapp.com/",
    date: "Dec 10 2024",
  },
  {
    title: "Tic Tac Toe",
    imgUrl: "https://github.com/christianbmartinez/tic-tac-toe/raw/main/md-image.jpg",
    alt: "Image for christians portfolio tic tac toe project",
    description:
      "A tic tac toe multiplayer game with chat. Built with Next, Socketio, and Express.",
    repo: "https://github.com/christianbmartinez/tic-tac-toe",
    href: "https://tictactoenextjs.netlify.app/",
    date: "Dec 10 2024",
  },
  {
    title: "Create Chattr App",
    imgUrl:
      "https://github.com/christianbmartinez/create-chattr-app/raw/main/public/createchattrapp.jpg",
    alt: "Image for christians portfolio create-chattr-app project",
    description: "A Nextjs chatbot boilerplate that uses the chattr library I authored.",
    repo: "https://github.com/christianbmartinez/create-chattr-app",
    href: "https://create-chattr-app.vercel.app/",
    date: "Dec 10 2024",
  },
  {
    title: "Logo Generator",
    imgUrl:
      "https://github.com/christianbmartinez/svg-logo-generator/raw/main/svglogogenerator.jpg",
    alt: "Image for christians portfolio SVG Logo generator project",
    description: "A node cli application for generating quality svg logos",
    repo: "https://github.com/christianbmartinez/svg-logo-generator",
    href: "https://drive.google.com/file/d/1Tg1iBDdUqCIz06HrNIAeVbb3j-26K3-V/view",
    date: "Dec 10 2024",
  },
];